# -*- coding: utf-8 -*-
"""Copy of Untitled20.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qhKitmqsgrSL9UQweKZiGcpCgHWUXvao
"""

import random

# Color codes
RED = "\033[91m"
GREEN = "\033[92m"
YELLOW = "\033[93m"
BLUE = "\033[94m"
CYAN = "\033[96m"
MAGENTA = "\033[95m"
WHITE = "\033[97m"
RESET = "\033[0m"

def number_guessing_game():
    best_score = None

    print(CYAN + "🎯 WELCOME TO THE NUMBER GUESSING GAME!\n" + RESET)

    while True:
        print(YELLOW + "Choose Difficulty Level:" + RESET)
        print(GREEN + "1. Easy (1 - 10)" + RESET)
        print(BLUE + "2. Medium (1 - 50)" + RESET)
        print(RED + "3. Hard (1 - 100)" + RESET)

        choice = input(CYAN + "Enter choice (1/2/3): " + RESET)

        if choice == '1':
            max_range = 10
        elif choice == '2':
            max_range = 50
        elif choice == '3':
            max_range = 100
        else:
            print(MAGENTA + "Invalid choice! Defaulting to Easy.\n" + RESET)
            max_range = 10

        secret = random.randint(1, max_range)
        attempts = 0

        print(CYAN + f"\nI have chosen a number between 1 and {max_range}. Try your luck!\n" + RESET)

        while True:
            try:
                guess = int(input(WHITE + "Enter your guess: " + RESET))
                attempts += 1
            except ValueError:
                print(RED + "⚠ Please enter a valid number!" + RESET)
                continue

            if guess < secret:
                print(YELLOW + "👉 Too LOW! Try again.\n" + RESET)
            elif guess > secret:
                print(YELLOW + "👆 Too HIGH! Try again.\n" + RESET)
            else:
                print(GREEN + f"🎉 CORRECT! You guessed it in {attempts} attempts!\n" + RESET)
                break

        if best_score is None or attempts < best_score:
            best_score = attempts
            print(MAGENTA + "🏆 NEW BEST SCORE!\n" + RESET)

        print(CYAN + f"📌 Best score so far: {best_score} attempts\n" + RESET)

        play_again = input(WHITE + "Do you want to play again? (yes/no): " + RESET).lower()
        print()
        if play_again != "yes":
            print(GREEN + "Thank you for playing! Goodbye 😊" + RESET)
            break


# Run the game
number_guessing_game()